defmodule FaithfulWordApi.MediaItemsSearch do
  import Ecto.Query

  require Logger

  def run(query, search_string, mediaCategory) do
    _run(query, normalize(search_string))
  end

  defmacro matching_media_items_and_score(search_string) do
    quote do
      fragment(
        """
        SELECT media_items_search.id AS id,
        ts_rank(
          media_items_search.document, plainto_tsquery(unaccent(?))
        ) AS score
        FROM media_items_search
        WHERE media_items_search.document @@ plainto_tsquery(unaccent(?))
        OR media_items_search.localizedname ILIKE ?
        """,
        ^unquote(search_string),
        ^unquote(search_string),
        ^"%#{unquote(search_string)}%"
      )
    end
  end

  defp _run(query, ""), do: query
  defp _run(query, search_string) do
    from media_item in query,
      join: id_and_score in matching_media_items_and_score(search_string),
      on: id_and_score.id == media_item.id,
      order_by: [desc: id_and_score.score]
  end

  defp normalize(search_string) do
    search_string
    |> String.downcase
    |> replace_abbreviations()

    search_string
    |> String.downcase
    |> String.replace(~r/\n/, " ")
    |> String.replace(~r/\t/, " ")
    |> String.replace(~r/\s{2,}/, " ")
    |> String.trim
  end

  def replace_abbreviations(search_string) do



    IO.inspect(Enum.find(packed_list, fn x -> "1 Chr" in elem(x, 1) end))
###
    # list = Enum.map(abbreviations(), fn ({abbrev, full}) ->
    #   downcased_abbrev = abbrev |> String.downcase
    #   # found = if Regex.match?( ~r/\b#{downcased_abbrev}\b/ , search_string) do
    #   #     Logger.info("found downcased_abbrev: #{downcased_abbrev} full: #{full}")
    #   # end
    #   # Logger.info("found: #{found}")

    #   Regex.replace(~r/\b#{downcased_abbrev}\b/, search_string, full)

    # end)
    # list
    # for x <- list, do: Logger.info("x: #{x}")

###

    # Enum.filter([1, 2, 3], fn x -> rem(x, 2) == 0 end)

    #   downcased_abbrev = k |> String.downcase
    #   replacement_string = if Regex.match?( ~r/\b#{downcased_abbrev}\b/ , search_string) do
    #     Logger.info("found #{downcased_abbrev} for #{v}")
    #     # new_search_string =
    #     Regex.replace(~r/\b#{downcased_abbrev}\b/, search_string, v)
    #   end
    # # end
    # Logger.info("replacement_string #{replacement_string}")
    # replacement_string
  end

  def abbreviations() do
    %{"1 Chr" => "1 Chronicles",
      "1 Ch" => "1 Chronicles",
      "1co" => "1 Corinthians",
      "1cr" => "1 Corinthians",
      "1cor" => "1 Corinthians",
      "1 Cor" => "1 Corinthians",
      "1 Co" => "1 Corinthians",
      "1 Cr" => "1 Corinthians",
      "1 Corinthians" => "1 Corinthians",
      "1 Jn" => "1 John",
      "1 Jhn" => "1 John",
      "1Jhn" => "1 John",
      "1 J" => "1 John",
      "1J" => "1 John",
      "1jn" => "1 John",
      "1john" => "1 John",
      "1 John" => "1 John",
      "1 Kgs" => "1 Kings",
      "1Kgs" => "1 Kings",
      "1 Kin" => "1 Kings",
      "1Kin" => "1 Kings",
      "1 Ki" => "1 Kings",
      "1Ki" => "1 Kings",
      "1K" => "1 Kings",
      "1 Kings" => "1 Kings",
      "1 Pet" => "1 Peter",
      "1 Pe" => "1 Peter",
      "1 Pt" => "1 Peter",
      "1 P" => "1 Peter",
      "1Pet" => "1 Peter",
      "1Pe" => "1 Peter",
      "1Pt" => "1 Peter",
      "1P" => "1 Peter",
      "1 Peter" => "1 Peter",
      "1 Sam" => "1 Samuel",
      "1 Sm" => "1 Samuel",
      "1 Sa" => "1 Samuel",
      "1 S" => "1 Samuel",
      "1Sam" => "1 Samuel",
      "1Sm" => "1 Samuel",
      "1Sa" => "1 Samuel",
      "1S" => "1 Samuel",
      "1 Samuel" => "1 Samuel",
      "1 Thess" => "1 Thessalonians",
      "1 Thes" => "1 Thessalonians",
      "1 Th" => "1 Thessalonians",
      "1 thesalonians" => "1 Thessalonians",
      "1 Ths" => "1 Thessalonians",
      "1Thess" => "1 Thessalonians",
      "1Thes" => "1 Thessalonians",
      "1Th" => "1 Thessalonians",
      "1thesalonians" => "1 Thessalonians",
      "1Ths" => "1 Thessalonians",
      "1 Thessalonians" => "1 Thessalonians",
      "1 Tim" => "1 Timothy",
      "1 Ti" => "1 Timothy",
      "1 Tm" => "1 Timothy",
      "1Tim" => "1 Timothy",
      "1Ti" => "1 Timothy",
      "1Tm" => "1 Timothy",
      "1 Timothy" => "1 Timothy",
      "2 Chr" => "2 Chronicles",
      "2 Ch" => "2 Chronicles",
      "2 Chron" => "2 Chronicles",
      "2Chr" => "2 Chronicles",
      "2Ch" => "2 Chronicles",
      "2Chron" => "2 Chronicles",
      "2 Chronicles" => "2 Chronicles",
      "2co" => "2 Corinthians",
      "2cr" => "2 Corinthians",
      "2cor" => "2 Corinthians",
      "2 Cor" => "2 Corinthians",
      "2 Co" => "2 Corinthians",
      "2 Cr" => "2 Corinthians",
      "2 Corinthians" => "2 Corinthians",
      "2 Jn" => "2 John",
      "2 Jhn" => "2 John",
      "2Jhn" => "2 John",
      "2 J" => "2 John",
      "2J" => "2 John",
      "2jn" => "2 John",
      "2john" => "2 John",
      "2 John" => "2 John",
      "2 Kgs" => "2 Kings",
      "2 Kin" => "2 Kings",
      "2 Ki" => "2 Kings",
      "2Kings" => "2 Kings",
      "2Kgs" => "2 Kings",
      "2Kin" => "2 Kings",
      "2Ki" => "2 Kings",
      "2 Kings" => "2 Kings",
      "2 Pet" => "2 Peter",
      "2 Pe" => "2 Peter",
      "2 Pt" => "2 Peter",
      "2 P" => "2 Peter",
      "2Pet" => "2 Peter",
      "2Pe" => "2 Peter",
      "2Pt" => "2 Peter",
      "2P" => "2 Peter",
      "2 Peter" => "2 Peter",
      "2 Sam" => "2 Samuel",
      "2 Sm" => "2 Samuel",
      "2 Sa" => "2 Samuel",
      "2 S" => "2 Samuel",
      "2Sam" => "2 Samuel",
      "2Sm" => "2 Samuel",
      "2Sa" => "2 Samuel",
      "2S" => "2 Samuel",
      "2 Samuel" => "2 Samuel",
      "2 Thess" => "2 Thessalonians",
      "2 Thes" => "2 Thessalonians",
      "2 Th" => "2 Thessalonians",
      "2 thesalonians" => "2 Thessalonians",
      "2 Ths" => "2 Thessalonians",
      "2Thess" => "2 Thessalonians",
      "2Thes" => "2 Thessalonians",
      "2Th" => "2 Thessalonians",
      "2thesalonians" => "2 Thessalonians",
      "2Ths" => "2 Thessalonians",
      "2 Thessalonians" => "2 Thessalonians",
      "2 Tim" => "2 Timothy",
      "2 Ti" => "2 Timothy",
      "2 Tm" => "2 Timothy",
      "2Tim" => "2 Timothy",
      "2Ti" => "2 Timothy",
      "2Tm" => "2 Timothy",
      "2 Timothy" => "2 Timothy",
      "3 Jn" => "3 John",
      "3 Jhn" => "3 John",
      "3Jhn" => "3 John",
      "3 J" => "3 John",
      "3 John" => "3 John",
      "ac" => "Acts",
      "act" => "Acts",
      "Acts" => "Acts",
      "am" => "Amos",
      "ams" => "Amos",
      "Amos" => "Amos",
      "Col" => "Colossians",
      "co" => "Colossians",
      "cl" => "Colossians",
      "colosians" => "Colossians",
      "Colossians" => "Colossians",
      "Dan" => "Daniel",
      "Da" => "Daniel",
      "Dn" => "Daniel",
      "dnl" => "Daniel",
      "Daniel" => "Daniel",
      "Deut" => "Deuteronomy",
      "De" => "Deuteronomy",
      "Dt" => "Deuteronomy",
      "Deuteronomy" => "Deuteronomy",
      "Eccl" => "Ecclesiastes",
      "Eccles" => "Ecclesiastes",
      "Eccle" => "Ecclesiastes",
      "Ecc" => "Ecclesiastes",
      "Ec" => "Ecclesiastes",
      "Ecclesiastes" => "Ecclesiastes",
      "ep" => "Ephesians",
      "ef" => "Ephesians",
      "eph" => "Ephesians",
      "ephes" => "Ephesians",
      "Ephesians" => "Ephesians",
      "Esth" => "Esther",
      "Est" => "Esther",
      "Es" => "Esther",
      "Esther" => "Esther",
      "Ex" => "Exodus",
      "Exod" => "Exodus",
      "Exodus" => "Exodus",
      "Ezek" => "Ezekiel",
      "Eze" => "Ezekiel",
      "Ezk" => "Ezekiel",
      "Ezekiel" => "Ezekiel",
      "Ezr" => "Ezra",
      "Ez" => "Ezra",
      "Ezra" => "Ezra",
      "Gal" => "Galatians",
      "Ga" => "Galatians",
      "gl" => "Galatians",
      "Galatians" => "Galatians",
      "Gen" => "Genesis",
      "Ge" => "Genesis",
      "Gn" => "Genesis",
      "Genesis" => "Genesis",
      "Hab" => "Habakkuk",
      "hk" => "Habakkuk",
      "Habakkuk" => "Habakkuk",
      "Hag" => "Haggai",
      "Hg" => "Haggai",
      "Haggai" => "Haggai",
      "he" => "Hebrews",
      "Heb" => "Hebrews",
      "hb" => "Hebrews",
      "hebr" => "Hebrews",
      "Hebrews" => "Hebrews",
      "Hos" => "Hosea",
      "Ho" => "Hosea",
      "Hosea" => "Hosea",
      "Isa" => "Isaiah",
      "Is" => "Isaiah",
      "Isaiah" => "Isaiah",
      "Jas" => "James",
      "Jm" => "James",
      "jam" => "James",
      "James" => "James",
      "Jer" => "Jeremiah",
      "Je" => "Jeremiah",
      "Jr" => "Jeremiah",
      "Jeremiah" => "Jeremiah",
      "Jb" => "Job",
      "Job" => "Job",
      "Jl" => "Joel",
      "jol" => "Joel",
      "Joel" => "Joel",
      "Jn" => "John",
      "Jhn" => "John",
      "jo" => "John",
      "John" => "John",
      "Jon" => "Jonah",
      "Jnh" => "Jonah",
      "Jonah" => "Jonah",
      "Josh" => "Joshua",
      "Jos" => "Joshua",
      "Jsh" => "Joshua",
      "Joshua" => "Joshua",
      "Jud" => "Jude",
      "Jd" => "Jude",
      "Judg" => "Judges",
      "Jdg" => "Judges",
      "Jg" => "Judges",
      "Jdgs" => "Judges",
      "jud" => "Judges",
      "Judges" => "Judges",
      "Lam" => "Lamentations",
      "La" => "Lamentations",
      "Lamentations" => "Lamentations",
      "Lev" => "Leviticus",
      "Le" => "Leviticus",
      "Lv" => "Leviticus",
      "Leviticus" => "Leviticus",
      "Lk" => "Luke",
      "Luk" => "Luke",
      "lu" => "Luke",
      "Luke" => "Luke",
      "Mal" => "Malachi",
      "Ml" => "Malachi",
      "Malachi" => "Malachi",
      "mk" => "Mark",
      "mar" => "Mark",
      "mr" => "Mark",
      "mrk" => "Mark",
      "Mark" => "Mark",
      "mt" => "Matthew",
      "mat" => "Matthew",
      "matt" => "Matthew",
      "Matthew" => "Matthew",
      "mic" => "Micah",
      "mi" => "Micah",
      "mc" => "Micah",
      "Micah" => "Micah",
      "na" => "Nahum",
      "nh" => "Nahum",
      "Nahum" => "Nahum",
      "Neh" => "Nehemiah",
      "Ne" => "Nehemiah",
      "Nehemiah" => "Nehemiah",
      "Num" => "Numbers",
      "Nu" => "Numbers",
      "Nm" => "Numbers",
      "Nb" => "Numbers",
      "Numbers" => "Numbers",
      "ob" => "Obadiah",
      "obah" => "Obadiah",
      "obd" => "Obadiah",
      "obdh" => "Obadiah",
      "Obadiah" => "Obadiah",
      "Philem" => "Philemon",
      "Phm" => "Philemon",
      "Pm" => "Philemon",
      "Philemon" => "Philemon",
      "Phil" => "Philippians",
      "Php" => "Philippians",
      "Pp" => "Philippians",
      "Phl" => "Philippians",
      "Ph" => "Philippians",
      "Philipians" => "Philippians",
      "Prov" => "Proverbs",
      "Pro" => "Proverbs",
      "Prv" => "Proverbs",
      "Pr" => "Proverbs",
      "pvb" => "Proverbs",
      "pvbs" => "Proverbs",
      "Ps" => "Psalms",
      "Psalm" => "Psalms",
      "Pslm" => "Psalms",
      "Psa" => "Psalms",
      "Psm" => "Psalms",
      "Psalms" => "Psalms",
      "Rev" => "Revelation",
      "Rv" => "Revelation",
      "re" => "Revelation",
      "apo" => "Revelation",
      "apoc" => "Revelation",
      "apocalypse" => "Revelation",
      "Revelation" => "Revelation",
      "Rom" => "Romans",
      "Ro" => "Romans",
      "Rm" => "Romans",
      "Romans" => "Romans",
      "Rth" => "Ruth",
      "Ru" => "Ruth",
      "Ruth" => "Ruth",
      "Song" => "Song of Solomon",
      "ss" => "Song of Solomon",
      "so" => "Song of Solomon",
      "Song of Solomon" => "Song of Solomon",
      "ti" => "Titus",
      "tit" => "Titus",
      "tits" => "Titus",
      "tts" => "Titus",
      "Titus" => "Titus",
      "Zech" => "Zechariah",
      "Zec" => "Zechariah",
      "Zc" => "Zechariah",
      "Zechariah" => "Zechariah",
      "Zeph" => "Zephaniah",
      "Zep" => "Zephaniah",
      "Zp" => "Zephaniah",
      "Zephaniah" => "Zephaniah"
    }
  end

  def packed_list() do
    %{"1 chronicles" => ["1 chr", "1 chr", "1 ch"],
    "1 corinthians" => ["1co", "1cr", "1cor", "1 cor", "1 co", "1 cr"],
    "1 john" => ["1 jn", "1 jhn", "1jhn", "1 j", "1j", "1jn", "1john"],
    "1 kings" => ["1kings", "1 kgs", "1kgs", "1 kin", "1kin", "1 ki", "1ki", "1k"],
    "1 peter" => ["1 pet", "1 pe", "1 pt", "1 p", "1pet", "1pe", "1pt", "1p"],
    "1 samuel" => ["1 sam", "1 sm", "1 sa", "1 s", "1sam", "1sm", "1sa", "1s"],
    "1 thessalonians" => ["1 thess", "1 thes", "1 th", "1 thesalonians", "1 ths", "1thess", "1thes", "1th", "1thesalonians", "1ths"],
    "1 timothy" => ["1 tim", "1 ti", "1 tm", "1tim", "1ti", "1tm"],
    "2 chronicles" => ["2 chr", "2 ch", "2 chron", "2chr", "2ch", "2chron"],
    "2 corinthians" => ["2co", "2cr", "2cor", "2 cor", "2 co", "2 cr"],
    "2 john" => ["2 jn", "2 jhn", "2jhn", "2 j", "2j", "2jn", "2john"],
    "2 kings" => ["2 kgs", "2 kin", "2 ki", "2kings", "2kgs", "2kin", "2ki"],
    "2 peter" => ["2 pet", "2 pe", "2 pt", "2 p", "2pet", "2pe", "2pt", "2p"],
    "2 samuel" => ["2 sam", "2 sm", "2 sa", "2 s", "2sam", "2sm", "2sa", "2s"],
    "2 thessalonians" => ["2 thess", "2 thes", "2 th", "2 thesalonians", "2 ths", "2thess", "2thes", "2th", "2thesalonians", "2ths"],
    "2 timothy" => ["2 tim", "2 ti", "2 tm", "2tim", "2ti", "2tm"],
    "3 john" => ["3 jn", "3 jhn", "3jhn", "3 j", "2j", "2jn", "2john"],
    "acts" => ["ac", "act"],
    "amos" => [ "am", "ams"],
    "colossians" => ["col", "co", "cl", "colosians"],
    "daniel" => ["dan", "da", "dn", "dnl"],
    "deuteronomy" => ["deut", "de", "dt"],
    "ecclesiastes" => ["eccl", "eccles", "eccle", "ecc", "ec"],
    "ephesians" => ["ep", "ef", "eph", "ephes"],
    "esther" => ["esth", "est", "es"],
    "exodus" => ["ex", "exod"],
    "ezekiel" => ["ezek", "eze", "ezk",],
    "ezra" => ["ezra", "ezr", "ez"],
    "galatians" => ["gal", "ga", "gl"],
    "genesis" => ["gen", "ge", "gn"],
    "habakkuk" => ["hab", "hk"],
    "haggai" => ["hag", "hg"],
    "hebrews" => ["he", "heb", "hb", "hebr"],
    "hosea" => ["hos", "ho"],
    "isaiah" => ["isa", "is"],
    "james" => ["jas", "jm", "jam"],
    "jeremiah" => ["jer", "je", "jr"],
    "job" => ["job", "jb"],
    "joel" => ["joel", "jl", "jol"],
    "john" => ["jn", "jhn", "jo"],
    "jonah" => ["jon", "jnh"],
    "joshua" => ["josh", "jos", "jsh"],
    "jude" => ["jude", "jud", "jd"],
    "judges" => ["judg", "jdg", "jg", "jdgs", "jud"],
    "lamentations" => ["lam", "la"],
    "leviticus" => ["lev", "le", "lv"],
    "luke" => ["lk", "luk", "lu"],
    "malachi" => ["mal", "ml"],
    "mark" => ["mk", "mar", "mr", "mrk"],
    "matthew" => ["mt", "mat", "matt"],
    "micah" => ["mic", "mi", "mc",],
    "nahum" => ["na", "nh",],
    "nehemiah" => ["neh", "ne"],
    "numbers" => ["num", "nu", "nm", "nb"],
    "obadiah" => [ "ob", "obah", "obd", "obdh"],
    "philemon" => ["philemon", "philem", "phm", "pm"],
    "philippians" => ["philipians", "phil", "php", "pp", "phl", "ph"],
    "proverbs" => ["prov", "pro", "prv", "pr", "pvb", "pvbs"],
    "psalms" => ["ps", "psalm", "pslm", "psa", "psm"],
    "revelation" => ["rev", "rv", "re", "apo", "apoc", "apocalypse"],
    "romans" => ["rom", "ro", "rm"],
    "ruth" => ["ruth", "rth", "ru"],
    "song of solomon" => ["song", "ss", "so"],
    "titus" =>["ti", "tit", "tits", "tts"],
    "zechariah" => ["zech", "zec", "zc"],
    "zephaniah" => ["zeph", "zep", "zp"]
    }
  end

  # IO.inspect(Enum.find(packed_list, fn x -> "1 Chr" in elem(x, 1) end))

end
