# https://docs.docker.com/compose/compose-file/
version: '3.7'
services:
  faithful_word:
    build: .
    depends_on:
      - postgres
    environment:
      FW_DATABASE_URL: ecto://faithful_word:faithful_word@postgres/faithful_word
      FW_HOSTNAME: localhost
      FW_PORT: 80
    labels:
      - "traefik.frontend.rule=Host:api.faithfulword.app"
      - "traefik.frontend.entryPoints=http,https"

  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: faithful_word
      POSTGRES_PASSWORD: faithful_word
      POSTGRES_USER: faithful_word
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

networks:
  default:
    external:
      name: web
