# https://docs.docker.com/compose/compose-file/
version: '3.7'
services:
  faithful_word:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ecto://faithful_word:faithful_word@postgres/faithful_word
      HOSTNAME: localhost
      PORT: 80
      # mix phx.gen.secret
      SECRET_KEY_BASE: fzBk8OEcI8thGxlypWPUqfR2w2WopdN8v8pmpuy2JNj2eerbYFnlecuVMrFPGYnW
    labels:
      - "traefik.frontend.rule=Host:api.faithfulword.app"
      - "traefik.frontend.entryPoints=http,https"

  postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_DB: faithful_word
      POSTGRES_PASSWORD: faithful_word
      POSTGRES_USER: faithful_word
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

networks:
  default:
    external:
      name: web
