use Mix.Config

# db ##########################################################################

# Configure your database
config :db, Db.Repo,
  username: System.get_env("FW_DB_USERNAME") || "postgres",
  password: System.get_env("FW_DB_PASSWORD") || "postgres",
  database: "faithful_word_dev",
  hostname: "localhost"

# Configure file upload
config :arc, storage: Arc.Storage.Local, asset_host: "http://localhost:4000"

# faithful_word ###############################################################

dev_secret = "8C6FsJwjV11d+1WPUIbkEH6gB/VavJrcXWoPLujgpclfxjkLkoNFSjVU9XfeNm6s"

# Configure your database
config :faithful_word, Db.Repo,
  database: "faithful_word_dev",
  pool_size: 10

# config :faithful_word, FaithfulWord.Mailer,
#   adapter: Bamboo.MailgunAdapter,
#   api_key: "key-6-lwae88m8q5gefyfzuv-k1j33f05666",
#   domain: "sandbox30725.mailgun.org"
# Mails
config :faithful_word, FaithfulWord.Mailer, adapter: Bamboo.LocalAdapter

# config :faithful_word, FaithfulWordApi.Auth.Guardian,
#   secret_key: "pnggot8GyQJKcPpPpnt1hZ1iGO9MZWkBd09+T6aJOQ2lK3ao6AnNgk0sCbydY8dW",
#   issuer: "FaithfulWordApi"

# General config
config :faithful_word,
  frontend_url: "http://localhost:3333/",
  oauth: [
    facebook: [
      client_id: "client_id",
      client_secret: "client_secret",
      redirect_uri: "http://localhost:3333/login/callback/facebook"
    ]
  ]

# Guardian
config :faithful_word,
       FaithfulWord.Authenticator.GuardianImpl,
       secret_key: dev_secret

# faithful_word_api ###########################################################

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :faithful_word_api, FaithfulWordApi.Endpoint,
  http: [port: 4000],
  # https: [port: 4443,
  #         otp_app: :phoenix_oauth2_mock_server,
  #         keyfile: "priv/keys/localhost.key",
  #         certfile: "priv/keys/localhost.cert"],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../apps/faithful_word_api/assets", __DIR__)
    ]
  ]

# config :faithful_word_api, FaithfulWordApi.Auth.Guardian,
#   issuer: "FaithfulWordApi",
#   secret_key: "ft8TBDLTR8kFdU253xYhBxzX6aTyJK+dJKkGGUo8Ju8vPCgo5IEX590sh6OgY0s6"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :faithful_word_api, FaithfulWordApi.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/faithful_word_api/{live,views}/.*(ex)$"
    ]
  ]

# General #####################################################################

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
