version: "3"
services:
  server:
    image: steveltn/https-portal:1
    container_name: nginx-server
    ports:
      - '80:80'
      - '443:443'
    environment:
      #STAGE: local
      DOMAINS: "objectaaron.com -> http://olivetree-server:5000/"
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
