# Global Configurations
global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'faithful_word_umbrella_app'

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'faithful_word_umbrella'
    static_configs:
      - targets: ['faithful_word_umbrella:4000']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
