version: "3"
services:
  db:
    image: postgres:10.4-alpine
    container_name: faithfulword-db
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=faithfulword_prod
    networks:
      - nginx-network
  admin:
    image: faithfulword-release
    container_name: faithfulword-admin
    build:
      context: .
      dockerfile: Dockerfile.run
    command: migrate
    networks:
      - nginx-network
    depends_on:
      - db
  server:
    image: faithfulword-release
    container_name: faithfulword-server
    environment:
      - PORT=5000
      - HOST="objectaaron.com"
    expose:
      - "5000"
    command: foreground
    networks:
      - nginx-network
    depends_on:
      - db
      - admin
networks:
  nginx-network:
    external: true
