FROM bitwalker/alpine-erlang:21.0.3

# Set environment variables
ENV MIX_ENV=prod

# Copy tarball release
ADD _build/prod/rel/faithfulword/releases/0.1.0/faithfulword.tar.gz ./

# Set user
USER default

# Set entrypoint
ENTRYPOINT ["./bin/faithfulword"]
